export const API_ACTION_FAIL = 'API_ACTION_FAIL';
export const API_ACTION_START = 'API_ACTION_START';
export const API_ACTION_SUCCESS = 'API_ACTION_SUCCESS';
export const NEW_DATA_REQUESTED = 'NEW_DATA_REQUESTED';
export const NEW_DATA_RECEIVED = 'NEW_DATA_RECEIVED';
export const NEW_DATA_FAILED = 'NEW_DATA_FAILED';
